### ISSUE TITLE
Moving Hawkeye to an org

### ISSUE THREAD

**Issue by felixhammerl** [hawkeye-sec/hawkeye#77]
### Description

In the interest of further development, I would love to move Hawkeye to an organization, so that we could easier add/remove folks and generally have development scale better. 

I would also propose to move the modules into their own repositories and use an `npm` org to group them into a common namespace. Greenkeeper will take care of having the modules all up to date in the downstream repository.

@Stono does this work for you?

**Comment by felixhammerl** [comment]
I have [created the org](https://github.com/hawkeye-sec), so I guess the call to action would be moving this repo over there, if that's ok. Forking over there would mean losing the issues and PRs, plus Github actually HTTP 302s if someone accesses the old URL.

**Comment by Stono** [comment]
Hey @felixhammerl - sorry for the delay.  Busy couple of days. 

Yes I'm totally OK with this, however before moving it can we think of any implications, for example:

  - I'll need to grant permission to things via SSO to the org, eg greenkeeper and travis (can you think of any others?)
  - Badges in the README will need updating
  - What are we doing about the image name on docker hub, it's still `stono/hawkeye`? 
  - A quick grep shows a few hardcoded `stono` links in code

**Comment by felixhammerl** [comment]
> I'll need to grant permission to things via SSO to the org, eg greenkeeper and travis (can you think of any others?)

In the org I can do that. Not a problem. More specifically, anyone with administrative privileges can do that, which is hard to scale in private repos

> Badges in the README will need updating
> A quick grep shows a few hardcoded stono links in code

I'll take care of that

> What are we doing about the image name on docker hub, it's still stono/hawkeye?

npm package can be deprecated with a notice to move to the org, or we can think of setting up a hook that deploys it under both names. Not sure whether docker allows the same. But in the description we can always give a deprecation notice and point to the org namespace.

**Comment by Stono** [comment]
Ok sounds like you've got most angles covered then.  Let me know when you'd like me to move it across

**Comment by felixhammerl** [comment]
Ready when you are :)

**Comment by felixhammerl** [comment]
awesome, thanks!
